### ISSUE TITLE
Hugo Extended is not working

### ISSUE THREAD

**Issue by fbrinker** [drone-plugins/drone-hugo#21]
~~To build Hugo with SASS support (the resources.ToCSS method is used), we need the extended version of Hugo.~~

~~See the [official docs for more information](https://gohugo.io/troubleshooting/faq/#i-get-tocss-this-feature-is-not-available-in-your-current-hugo-version).~~

~~Would that be possible? :)~~

Okay I found out it's already implemented, But i have no idea how to set the `extended` flag.
It looks like I have to use
```
settings:
  extended: true
```
But my build fails with `2019/11/12 22:15:12 : unexpected EOF`

The build works on my machine with `Hugo Static Site Generator v0.59.1/extended linux/amd64`

## I've set up a minimal demo:
https://git.f-brinker.de/fbrinker/drone-hugo-extended-demo
https://drone.f-brinker.de/fbrinker/drone-hugo-extended-demo/2/1/3

## Important parts:
* [SCSS compiling](https://git.f-brinker.de/fbrinker/drone-hugo-extended-demo/src/branch/master/layouts/partials/scss.html)
* [Drone config](https://git.f-brinker.de/fbrinker/drone-hugo-extended-demo/src/branch/master/.drone.yml)
* [Failed normal build](https://drone.f-brinker.de/fbrinker/drone-hugo-extended-demo/2/1/2), as **expected**, due ToCSS is not working
* [Failed extended build](https://drone.f-brinker.de/fbrinker/drone-hugo-extended-demo/2/1/3), should work, but I get the **EOF error**.

**Comment by tboerger** [comment]
Generally the `extended` attribute is the right one. The drone plugins are getting the settings applied as env variables with a plugin_ prefix.

@cbrgm could you look into that?

**Comment by fbrinker** [comment]
Okay I've found the error. If you specify the `extended` flag, but no version, it fails to download the binary. because it doesn't fallback to the buildInVersion number. 

An easy fix... I will create a PR for that. But even with a working download (specified the version in the following build), I get a follow-up error:
https://drone.f-brinker.de/fbrinker/drone-hugo-extended-demo/5/1/4
```
+ /tmp/191382620/193183243 check
--
2 | 2019/11/13 11:51:35 fork/exec /tmp/191382620/193183243: no such file or directory
```

**Comment by tboerger** [comment]
Ok, looks like it's really time to say good bye to the current approach of this plugin. We should really tag this image based on the shipped hugo version and directly embed the extended hugo version.

**Comment by fbrinker** [comment]
Would be an idea.

Debugged the problem above for an hour now and I don't get it... The file has to be there when the exec.Command is initialized and .Run afterwards...

Changed the code a bit and the binary path/name (see the "comments" in the output // for details)
```
/tmp/hugo-283031025 // new path
0 // size before the download / copy
Copying hugo binary...
Returning Path.../tmp/hugo-283031025
41653360 // size after the copy command
exists // check if the file exists before the exec.Command
[] // args
2019/11/13 13:13:08 fork/exec /tmp/hugo-283031025: no such file or directory
```

![confused gof](https://media1.giphy.com/media/CPskAi4C6WLHa/giphy.gif?cid=790b7611b6bbe928744d6b246f7a113c5cce7c093c46f498&rid=giphy.gif)

**Comment by cbrgm** [comment]
@fbrinker Thanks for your work so far! I checked out your PR #22 and tried to reproduce the issue. This is really strange and I currently try to figure out the reason for that..

Even more strange is that the ´validate´ flag which triggers the ´hugo check´ command before generating the site assets works fine.

```
docker run --rm \
  -e PLUGIN_HUGO_VERSION=0.59.1 \
  -e PLUGIN_EXTENDED=true \
  -e PLUGIN_BUILDDRAFTS=false \
  -e PLUGIN_BUILDEXPIRED=false \
  -e PLUGIN_BUILDFUTURE=false \
  -e PLUGIN_VALIDATE=true \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  plugins/hugo:latest
+ /tmp/357385695/366575538 check // works!
2019/11/20 14:44:05 fork/exec /tmp/357385695/366575538: no such file or directory
´´´

**Comment by fbrinker** [comment]
Can we reopen this due to the strange follow-up bug?

This is really strange. I'm wondering if there are any dependency issues with the container and building the site with hugo extended "uses" sth else than the normal hugo or the hugo check command... but since it's a go binary, there shouldn't be any dependencies to the host?

Since it works fine on other systems, could it be a problem with the container itself?

**Comment by hypervtechnics** [comment]
Are there any news on this? @cbrgm

**Comment by hypervtechnics** [comment]
Whatever the issue is... Here is a working hugo plugin only using the extended version: https://github.com/hypervtechnics/drone-hugo

**Comment by mlthlschr** [comment]
@hypervtechnics thanks for the workaround. but would be great if the official package could achieve that as well. maybe i find time to debug some day but don't know any go until now

**Comment by mgstoptal** [comment]
The problem is that hugo extended needs glibc which isn't in alpine. Something like this in .drone.yml works for me:
```
---
kind: pipeline
name: whatever

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.69.0
    extended: true
    validate: true
    config: config.toml
    content: content
  commands:
    - apk add libc6-compat libstdc++
    - /bin/drone-hugo
```

**Comment by tboerger** [comment]
Does it work for you now?

**Comment by mlthlschr** [comment]
yes, it does! thanks a lot!
