### ISSUE TITLE
_index.md in root content directory not rendering 

### ISSUE THREAD

**Issue by rkling01** [drone-plugins/drone-hugo#23]
Hi,
I'm having an issue related to an upgrade to 0.58.3.

For some reason the _index.md file in the content directory isn't rendering any of the markdown - I get the navigation and other content but just not seeing anything else on the page related to the markdown so the net result is the page is blank.

Just to clarify - all the other _index.md files in different directories under content render fine - its just the _index.md in the root of the content directory (which would be the page that renders when the site is launched).

On my desktop - 0.59.1 seems to work fine so having a tough time recreating this issue locally.  

Any thoughts on what might be happening? Thanks!

https://discourse.drone.io/t/drone-hugo-plugin-question/6560

**Comment by tboerger** [comment]
As the Discourse post shows, this issue is related to Hugo, not really to this plugin.
