### ISSUE TITLE
Add post-build script

### ISSUE THREAD

**Issue by vbrandl** [drone-plugins/drone-hugo#6]
I like to compress my hugo output ahead of time to prevent the webserver from compressing the files on the fly on each request.

I do this using a Makefile. It would be cool to have a parameter for this plugin to execute custom commands after the hugo build has finished.

**Comment by tboerger** [comment]
Really no need to integrate that into the Hugo plugin, just add another step to your drone pipeline.

**Comment by vbrandl** [comment]
Oh yeah, you are right. That's actually the nicer way. Thanks.
